name: push
on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-2
  schedule:
    - cron: '10 4 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@main
        env:
          OCI_ROOT_URL: https://bundle.bar
          OCI_NAMESPACE: u/${{ secrets.BB_USER }}/oci-conformance-2/primary
          OCI_CROSSMOUNT_NAMESPACE: u/${{ secrets.BB_USER }}/oci-conformance-2/secondary
          OCI_USERNAME: ${{ secrets.BB_USER }}
          OCI_PASSWORD: ${{ secrets.BB_TOKEN }}
          OCI_TEST_PUSH: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: oci-test-results-2-${{ github.sha }}
          path: |
            report.html
            junit.xml
